name: 'DynatraceAction'
description: 'Action that sends metrics and events to a Dynatrace monitoring environment from a GitHub workflow'
author: 'Wolfgang Beer'
inputs:
  url: 
    required: true
    description: 'A valid Dynatrace URL'
  token:
    required: true
    description: 'A valid Dynatrace API-token'
  metrics:
    description: 'A list of metrics objects to send'
    default: '[]'
  events:
    description: 'A list of event objects to send'
    default: '[]'
  workflowCompleted:
    description: 'True for sending a workflow completed event'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'bar-chart-2'
  color: 'black'
